version: "3.8"

services:
  backend:
    container_name: backend-basecrm-trade
    build: ./backend-basecrm-trade/
    restart: unless-stopped
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env

  frontend:
    container_name: frontend-basecrm-trade
    build: ./frontend-basecrm-trade
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - ${CLIENT_PORT}:80
    env_file:
      - .env


